### ISSUE TITLE
什么怪东西（）

### ISSUE THREAD

**Issue by wuyilingwei** [Baka632/My-Chao-Love-Story#1]
建议加点涩涩

**Comment by Baka632** [comment]
这东西怎么加啊（笑）~

**Comment by Baka632** [comment]
嗯，我不想加这东西...
~其实是因为不好构思出相关情节~

如果需要，你可以自己 fork，然后随便改~

(毕竟这个程序的许可证是 MIT)

**Comment by wuyilingwei** [comment]
~你说的好像我就会写h文了似的~

**Comment by Baka632** [comment]
~其实是怕仓库被举报~
~但也是真的写不出来（）~
